"""chapter_overviews cache: the chapter overview Markdown + its generation gate.

Owns chapter_overviews. The overview is generated by watching the chapter video
through Gemini and streamed to the page; this row caches the finished Markdown so
a revisit reads it instantly. A small claim/mark machine (pending -> generating
-> ready/failed), atomic via ON CONFLICT, stops two SSE generators racing the
same chapter (mirrors services/gemini_file_service.py).

candidate_id pins the chosen candidate the overview came from: a re-pick is
treated as stale and regenerated. There is NO time expiry (unlike the Gemini
file) — only a re-pick invalidates. A `generating` row whose generator died
mid-stream (disconnect) is reclaimable after a short staleness window so the
next visit regenerates instead of waiting forever.
"""

import uuid
from dataclasses import dataclass
from typing import Literal

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from models.chapter_overview import ChapterOverview

# A cached overview is reusable only when ready AND from the current candidate
# (re-pick invalidates). A `generating` row counts as "in flight" only while
# fresh — a stale one (generator died) is reclaimable.
_FRESH = (
    "chapter_overviews.status = 'ready' "
    "AND chapter_overviews.candidate_id = :candidate_id"
)
_RECENT_GENERATING = (
    "chapter_overviews.status = 'generating' "
    "AND chapter_overviews.updated_at > now() - interval '3 minutes'"
)

# Atomic claim: flip to 'generating' UNLESS a fresh overview exists or another
# generator is actively running. RETURNING tells us whether we won.
_CLAIM_SQL = text(
    f"""
    INSERT INTO chapter_overviews
        (id, chapter_id, candidate_id, status, created_at, updated_at)
    VALUES (:id, :chapter_id, :candidate_id, 'generating', now(), now())
    ON CONFLICT (chapter_id) DO UPDATE
        SET status = 'generating',
            candidate_id = :candidate_id,
            markdown = NULL,
            error_type = NULL,
            updated_at = now()
        WHERE NOT ({_FRESH})
          AND NOT ({_RECENT_GENERATING})
    RETURNING id
    """
)


@dataclass
class OverviewSnapshot:
    """A fast read for the GET endpoint. markdown is set only when ready+fresh."""

    status: Literal["ready", "pending", "generating", "failed"]
    markdown: str | None
    # Set for `failed` rows: the AIError code recorded by mark_failed. The
    # materialize step uses it to tell transient failures (retry) from verdicts.
    error_type: str | None = None


async def _get(db: AsyncSession, chapter_id: uuid.UUID) -> ChapterOverview | None:
    result = await db.execute(
        select(ChapterOverview).where(ChapterOverview.chapter_id == chapter_id)
    )
    return result.scalar_one_or_none()


async def read_ready(
    db: AsyncSession, *, chapter_id: uuid.UUID, candidate_id: uuid.UUID
) -> str | None:
    """The ready Markdown for this chapter+candidate, else None (regenerate)."""
    row = await _get(db, chapter_id)
    if (
        row is None
        or row.status != "ready"
        or row.candidate_id != candidate_id
        or not row.markdown
    ):
        return None
    return row.markdown


async def read_snapshot(
    db: AsyncSession, *, chapter_id: uuid.UUID, candidate_id: uuid.UUID
) -> OverviewSnapshot:
    """GET 快读: ready+fresh -> the Markdown; otherwise a status the page uses to
    decide it should open the SSE stream (a re-pick reads as not-ready)."""
    row = await _get(db, chapter_id)
    if row is None:
        return OverviewSnapshot(status="pending", markdown=None)
    if row.status == "ready" and row.candidate_id == candidate_id and row.markdown:
        return OverviewSnapshot(status="ready", markdown=row.markdown)
    if row.status == "failed":
        return OverviewSnapshot(
            status="failed", markdown=None, error_type=row.error_type
        )
    if row.status == "generating":
        return OverviewSnapshot(status="generating", markdown=None)
    # pending, or ready-but-stale (re-pick): the page should (re)generate.
    return OverviewSnapshot(status="pending", markdown=None)


async def claim_for_generate(
    db: AsyncSession, *, chapter_id: uuid.UUID, candidate_id: uuid.UUID
) -> bool:
    """Try to own the generation. False -> fresh already / another active run."""
    result = await db.execute(
        _CLAIM_SQL,
        {"id": uuid.uuid4(), "chapter_id": chapter_id, "candidate_id": candidate_id},
    )
    await db.commit()
    return result.first() is not None


async def mark_ready(
    db: AsyncSession,
    *,
    chapter_id: uuid.UUID,
    candidate_id: uuid.UUID,
    markdown: str,
) -> None:
    row = await _get(db, chapter_id)
    if row is None:
        return  # row swept mid-generate (unlikely); drop the result
    row.status = "ready"
    row.candidate_id = candidate_id
    row.markdown = markdown
    row.error_type = None
    await db.commit()


async def mark_failed(
    db: AsyncSession, *, chapter_id: uuid.UUID, error_type: str | None
) -> None:
    row = await _get(db, chapter_id)
    if row is None:
        return
    row.status = "failed"
    row.error_type = (error_type or "")[:200] or None
    await db.commit()
