"""question bank tables

Additive only (向前兼容): the XKW question bank's local copy (questions,
question_versions), user question sets + items, answering sessions + graded
question attempts, the basic-data cache and the XKW call ledger.

Revision ID: b3da7b4eccfe
Revises: e6f1a3c8b2d7
Create Date: 2026-09-25 15:42:26.741324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3da7b4eccfe'
down_revision: Union[str, Sequence[str], None] = 'e6f1a3c8b2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qbank_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('use_case', sa.String(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_code', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('question_set_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qbank_usage_logs_created_at', 'qbank_usage_logs', ['created_at'], unique=False)
    op.create_index('ix_qbank_usage_logs_user_id_created_at', 'qbank_usage_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('xkw_course_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.String(), nullable=True),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('objective', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('answer_scoreable', sa.Boolean(), nullable=True),
    sa.Column('media_flag', sa.Integer(), nullable=True),
    sa.Column('stem_html', sa.Text(), nullable=False),
    sa.Column('answer_html', sa.Text(), server_default='', nullable=False),
    sa.Column('explanation_html', sa.Text(), server_default='', nullable=False),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_hash', sa.String(), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_questions_provider_external_id')
    )
    op.create_table('xkw_catalog_cache',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('kind', 'key')
    )
    op.create_table('question_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('parser_version', sa.Integer(), nullable=False),
    sa.Column('content_version', sa.String(), nullable=False),
    sa.Column('structure', sa.String(), nullable=False),
    sa.Column('view_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slot_map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parse_status', sa.String(), nullable=False),
    sa.Column('degraded_slot_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fully_auto', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parse_status in ('parsed', 'raw', 'failed')", name='ck_question_versions_parse_status'),
    sa.CheckConstraint("structure in ('parsed', 'raw')", name='ck_question_versions_structure'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'content_version', name='uq_question_versions_question_id_content_version')
    )
    op.create_index('ix_question_versions_question_id_is_current', 'question_versions', ['question_id', 'is_current'], unique=False)
    op.create_table('question_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('origin_kind', sa.String(), nullable=False),
    sa.Column('query_spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind in ('quiz', 'assignment', 'practice', 'paper')", name='ck_question_sets_kind'),
    sa.CheckConstraint("mode in ('batch', 'immediate')", name='ck_question_sets_mode'),
    sa.CheckConstraint("origin_kind in ('dev')", name='ck_question_sets_origin_kind'),
    sa.CheckConstraint("status in ('generating', 'ready', 'empty', 'failed')", name='ck_question_sets_status'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_sets_spec_hash_created_at', 'question_sets', ['spec_hash', 'created_at'], unique=False)
    op.create_index('ix_question_sets_user_id_updated_at', 'question_sets', ['user_id', 'updated_at'], unique=False)
    op.create_table('question_set_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_set_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("mode in ('batch', 'immediate')", name='ck_question_set_attempts_mode'),
    sa.CheckConstraint("status in ('open', 'submitted')", name='ck_question_set_attempts_status'),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_set_attempts_user_id_set_id_started_at', 'question_set_attempts', ['user_id', 'question_set_id', 'started_at'], unique=False)
    op.create_index('uq_question_set_attempts_user_id_set_id_open', 'question_set_attempts', ['user_id', 'question_set_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('question_set_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_set_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_set_id', 'order_index', name='uq_question_set_items_set_id_order_index')
    )
    op.create_table('question_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attempt_session_id', sa.UUID(), nullable=False),
    sa.Column('question_version_id', sa.UUID(), nullable=False),
    sa.Column('responses_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slot_results_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_earned', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('client_submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status in ('graded', 'ungradable', 'pending')", name='ck_question_attempts_status'),
    sa.ForeignKeyConstraint(['attempt_session_id'], ['question_set_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_session_id', 'question_version_id', name='uq_question_attempts_session_id_version_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_attempts')
    op.drop_table('question_set_items')
    op.drop_index('uq_question_set_attempts_user_id_set_id_open', table_name='question_set_attempts', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_question_set_attempts_user_id_set_id_started_at', table_name='question_set_attempts')
    op.drop_table('question_set_attempts')
    op.drop_index('ix_question_sets_user_id_updated_at', table_name='question_sets')
    op.drop_index('ix_question_sets_spec_hash_created_at', table_name='question_sets')
    op.drop_table('question_sets')
    op.drop_index('ix_question_versions_question_id_is_current', table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_table('xkw_catalog_cache')
    op.drop_table('questions')
    op.drop_index('ix_qbank_usage_logs_user_id_created_at', table_name='qbank_usage_logs')
    op.drop_index('ix_qbank_usage_logs_created_at', table_name='qbank_usage_logs')
    op.drop_table('qbank_usage_logs')
    # ### end Alembic commands ###
