import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, ForeignKey, String, Text, func
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class ChapterOverview(Base):
    """Cached learning-oriented Markdown overview for a chapter (生成自本章视频).

    One row per chapter (1:1). The overview is generated by watching the
    chapter's video through Gemini (shares chapter_gemini_files with the
    companion — zero re-transfer) and streamed to the page; this row caches the
    finished Markdown so a revisit reads it instantly without regenerating.

    candidate_id pins WHICH chosen candidate the overview was written from: a
    re-pick (chapter.chosen_candidate_id changes) makes it stale and it
    regenerates. status is a small claim/mark machine (pending -> generating ->
    ready/failed) so two SSE generators never race the same chapter. A mid-stream
    disconnect leaves status at `generating` (no half markdown is stored); the
    next visit re-claims and regenerates (the video is already cached, so it's
    one model call, no re-upload).
    """

    __tablename__ = "chapter_overviews"
    __table_args__ = (
        CheckConstraint(
            "status in ('pending', 'generating', 'ready', 'failed')",
            name="ck_chapter_overviews_status",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    # 1:1 with chapter — UNIQUE so a chapter never accumulates two overview rows.
    chapter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("course_chapters.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    # Which chosen candidate this overview was written from; a re-pick makes it
    # stale. CASCADE so deleting the candidate clears the cache too. Nullable so
    # a pending row can exist before the candidate is pinned.
    candidate_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("chapter_video_candidates.id", ondelete="CASCADE"),
        nullable=True,
    )
    status: Mapped[str] = mapped_column(String, nullable=False)
    # The finished overview Markdown — only set once status flips to 'ready'.
    markdown: Mapped[str | None] = mapped_column(Text, nullable=True)
    error_type: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
