"""Chapter overview endpoints: fast cached read + SSE real-time generation.

Course-scoped under /courses/{course_id}/chapters/{chapter_id}/overview. The
overview is a learning-oriented Markdown note generated by watching the chapter
video through Gemini (shares chapter_gemini_files with the companion — zero
re-transfer). Two endpoints:

- GET  .../overview         -> ChapterOverviewOut (ready ⇒ markdown, else open SSE);
- GET  .../overview/stream  -> SSE (reuses ai/streaming encode_chunk: preparing
  while the video uploads, reasoning, delta=markdown, usage, done, error).

IDOR: course ownership + the chapter having a chosen video are enforced before
streaming (foreign / unknown / no-video all collapse to 404). A claim machine
(course_overview_service) stops concurrent duplicate generation; a mid-stream
disconnect leaves the row `generating` and the next visit regenerates (the video
is already cached, so it's one model call, no re-upload).
"""

import asyncio
import contextlib
import uuid
from collections.abc import AsyncIterator

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession

from ai import AIChunk, AIUseCase, ai_client, encode_chunk
from core import aio
from core.database import AsyncSessionLocal, get_db
from core.security import CurrentUser, get_current_user
from schemas.overview import ChapterOverviewOut
from services import (
    chapter_gemini_prep,
    course_overview_service,
    course_service,
    video_asset_service,
)

router = APIRouter(prefix="/courses", tags=["overview"])

_NOT_FOUND = HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="not_found")

# The user-turn instruction; the structure/style lives in the COURSE_OVERVIEW
# system prompt (rules 第八章: prompts in templates, not business code).
_OVERVIEW_INSTRUCTION = "请基于本章节视频，为正在学习这一章的学生写一份学习向的章节概述。"

# While another tab is already generating, wait for its result this often.
_LOST_POLL_S = 2.0
_LOST_MAX_TICKS = 90  # ~3 min ceiling, then surface a retryable error


async def _persist_ready(
    chapter_id: uuid.UUID, candidate_id: uuid.UUID, markdown: str
) -> None:
    async with AsyncSessionLocal() as db:
        await course_overview_service.mark_ready(
            db, chapter_id=chapter_id, candidate_id=candidate_id, markdown=markdown
        )


async def _persist_failed(chapter_id: uuid.UUID, error_type: str | None) -> None:
    async with AsyncSessionLocal() as db:
        await course_overview_service.mark_failed(
            db, chapter_id=chapter_id, error_type=error_type
        )


def _cached(markdown: str) -> list[str]:
    """Emit a ready overview over SSE as one delta + done (same chat protocol)."""
    return [
        encode_chunk(AIChunk(kind="delta", text=markdown)),
        encode_chunk(AIChunk(kind="done")),
    ]


async def _generate(
    *,
    course_id: uuid.UUID,
    user_id: uuid.UUID,
    chapter_id: uuid.UUID,
    candidate_id: uuid.UUID,
) -> AsyncIterator[str]:
    """Ensure the chapter's Gemini file (preparing), then stream the overview
    Markdown and persist it on a clean done. A disconnect before `done` leaves the
    row `generating` (no half note stored) so a later visit regenerates."""
    video = None
    async for event in chapter_gemini_prep.stream_until_usable(
        chapter_id=chapter_id, candidate_id=candidate_id
    ):
        if event.kind == "preparing":
            yield encode_chunk(AIChunk(kind="preparing"))
        elif event.kind == "ready":
            video = event.video
            break
        else:  # unavailable / failed — overview can't be made without the video
            await _persist_failed(chapter_id, f"video_{event.kind}")
            yield encode_chunk(
                AIChunk(
                    kind="error",
                    error_code="overview_video_unavailable",
                    error_message="本章视频暂不可用，无法生成概述",
                )
            )
            return
    if video is None:
        await _persist_failed(chapter_id, "video_unavailable")
        yield encode_chunk(
            AIChunk(
                kind="error",
                error_code="overview_video_unavailable",
                error_message="本章视频暂不可用，无法生成概述",
            )
        )
        return

    parts: list[str] = []
    persist_task: asyncio.Task | None = None
    done_seen = False
    failed_code: str | None = None

    def ensure_persist_scheduled() -> None:
        nonlocal persist_task
        markdown = "".join(parts)
        if persist_task is None and markdown:
            persist_task = aio.spawn_protected(
                _persist_ready(chapter_id, candidate_id, markdown)
            )

    chunk_stream = ai_client.stream_ask_video(
        AIUseCase.COURSE_OVERVIEW,
        video,
        _OVERVIEW_INSTRUCTION,
        history=[],
        user_id=str(user_id),
        course_id=str(course_id),
    )
    try:
        async for chunk in chunk_stream:
            if chunk.kind == "delta" and chunk.text:
                parts.append(chunk.text)
            elif chunk.kind == "done":
                done_seen = True
                ensure_persist_scheduled()
            elif chunk.kind == "error":
                failed_code = chunk.error_code
            yield encode_chunk(chunk)
    finally:
        if done_seen:
            ensure_persist_scheduled()
        elif failed_code is not None:
            aio.spawn_protected(_persist_failed(chapter_id, failed_code))
        # else: disconnected mid-stream -> leave `generating` for reclaim.
        with contextlib.suppress(Exception):
            await chunk_stream.aclose()
        if persist_task is not None and not persist_task.done():
            with contextlib.suppress(asyncio.CancelledError):
                await asyncio.shield(persist_task)


async def _overview_event_stream(
    *,
    course_id: uuid.UUID,
    user_id: uuid.UUID,
    chapter_id: uuid.UUID,
    candidate_id: uuid.UUID,
) -> AsyncIterator[str]:
    """ready ⇒ emit it; else claim and generate; else wait for the active run."""
    async with AsyncSessionLocal() as db:
        cached = await course_overview_service.read_ready(
            db, chapter_id=chapter_id, candidate_id=candidate_id
        )
    if cached is not None:
        for frame in _cached(cached):
            yield frame
        return

    async with AsyncSessionLocal() as db:
        won = await course_overview_service.claim_for_generate(
            db, chapter_id=chapter_id, candidate_id=candidate_id
        )
    if won:
        async for frame in _generate(
            course_id=course_id,
            user_id=user_id,
            chapter_id=chapter_id,
            candidate_id=candidate_id,
        ):
            yield frame
        return

    # Another generator is active — wait for its result (or take over if it fails).
    for _tick in range(_LOST_MAX_TICKS):
        async with AsyncSessionLocal() as db:
            cached = await course_overview_service.read_ready(
                db, chapter_id=chapter_id, candidate_id=candidate_id
            )
        if cached is not None:
            for frame in _cached(cached):
                yield frame
            return
        async with AsyncSessionLocal() as db:
            snapshot = await course_overview_service.read_snapshot(
                db, chapter_id=chapter_id, candidate_id=candidate_id
            )
            take_over = snapshot.status == "failed" and (
                await course_overview_service.claim_for_generate(
                    db, chapter_id=chapter_id, candidate_id=candidate_id
                )
            )
        if take_over:
            async for frame in _generate(
                course_id=course_id,
                user_id=user_id,
                chapter_id=chapter_id,
                candidate_id=candidate_id,
            ):
                yield frame
            return
        yield encode_chunk(AIChunk(kind="preparing"))
        await asyncio.sleep(_LOST_POLL_S)

    yield encode_chunk(
        AIChunk(
            kind="error",
            error_code="overview_timeout",
            error_message="概述生成超时，请稍后重试",
        )
    )


async def _resolve_candidate(
    db: AsyncSession, *, user_id: uuid.UUID, course_id: uuid.UUID, chapter_id: uuid.UUID
) -> uuid.UUID:
    """Course ownership + the chapter's chosen candidate, or raise 404 (IDOR)."""
    course = await course_service.get_owned_course(
        db, user_id=user_id, course_id=course_id
    )
    if course is None:
        raise _NOT_FOUND
    candidate_id = await video_asset_service.get_chapter_chosen_candidate_id(
        db, course_id=course_id, chapter_id=chapter_id
    )
    if candidate_id is None:
        # Overview needs a video — no chosen candidate is a 404 (IDOR-safe).
        raise _NOT_FOUND
    return candidate_id


@router.get(
    "/{course_id}/chapters/{chapter_id}/overview",
    response_model=ChapterOverviewOut,
)
async def read_chapter_overview(
    course_id: uuid.UUID,
    chapter_id: uuid.UUID,
    current_user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> ChapterOverviewOut:
    candidate_id = await _resolve_candidate(
        db, user_id=current_user.id, course_id=course_id, chapter_id=chapter_id
    )
    snapshot = await course_overview_service.read_snapshot(
        db, chapter_id=chapter_id, candidate_id=candidate_id
    )
    return ChapterOverviewOut(status=snapshot.status, markdown=snapshot.markdown)


@router.get("/{course_id}/chapters/{chapter_id}/overview/stream")
async def stream_chapter_overview(
    course_id: uuid.UUID,
    chapter_id: uuid.UUID,
    current_user: CurrentUser = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> StreamingResponse:
    candidate_id = await _resolve_candidate(
        db, user_id=current_user.id, course_id=course_id, chapter_id=chapter_id
    )
    return StreamingResponse(
        _overview_event_stream(
            course_id=course_id,
            user_id=current_user.id,
            chapter_id=chapter_id,
            candidate_id=candidate_id,
        ),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )
